apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: LoadBalancer
  selector:
    app: fastapi

  ports:
  - port: 3333
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  
  template:
    metadata:
      labels:
        app: fastapi
    
    spec:
      containers:
      - name: fastapi
  
        image: anemus/simple_fast_api
    
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            cpu:     250m
            memory:  128Mi
        ports:
        - containerPort: 8000